# Generated by Django 5.0.2 on 2024-03-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('honorrs', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('github', models.URLField()),
                ('phone', models.CharField(max_length=15)),
                ('school', models.CharField(max_length=100)),
                ('specialized', models.CharField(max_length=100)),
                ('gpa', models.CharField(max_length=10)),
                ('code', models.TextField()),
                ('tech', models.TextField()),
                ('image', models.ImageField(upload_to='cv_images/')),
            ],
        ),
    ]
