# Generated by Django 3.2.25 on 2024-03-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gendercv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
